upload_dir: "uploads"
nmparse_url: "https://api.ideaconsult.net/gracious/enm/gracious/nmparser"
SOLR_ROOT: "https://solr-kc.ideaconsult.net/solr/"
SOLR_VECTOR: "spectrum_p1024"
SOLR_COLLECTIONS:
  default: "charisma"
  collections:
    - name: "charisma"
      description: "CHARISMA"
      roles: ["public"]
    - name: "charisma_protected"
      description: "CHARISMA protected"
      roles: ["charisma"]
KEYCLOAK:
  SERVER_URL: "https://iam.ideaconsult.net/"
  REALM_NAME: "nano"
  CLIENT_ID: "idea-ui"
  CLIENT_SECRET: "secret"