upload_dir: "uploads"
nmparse_url: "https://api.ideaconsult.net/gracious/enm/gracious/nmparser"
SOLR_ROOT: "https://solr-kc.ideaconsult.net/solr/"
SOLR_VECTOR: "spectrum_p1024"
SOLR_COLLECTIONS:
  default: "charisma"
  collections:
    - name: "charisma"
      description: "CHARISMA"
      license: "TBD"
      roles: ["public"]
    - name: "charisma_protected"
      description: "CHARISMA protected"
      license: "TBD"
      roles: ["charisma", "test-role-1"]
SOLR_FIELDS:
  - name: "Sample"
    field: "name_s"
    type: "text"
    icon: "fa-solid fa-font"
    use: "dynamic"
  - name: "Material"
    field: "publicname_s"
    type: "text"
    icon: "fa-solid fa-box"
    use: "predefined"
  - name: "Instrument"
    field: "instrument_s"
    type: "text"
    icon: "fa-solid fa-microscope"
    use: "dynamic"
  - name: "Data provider"
    field: "reference_owner_s"
    type: "text"
    icon: "fa-solid fa-user"
    use: "predefined"
  - name: "Investigation"
    field: "reference_s"
    type: "text"
    icon: "fa-solid fa-book"
    use: "predefined"
  - name: "Method"
    field: "E.method_s"
    type: "text"
    icon: "fa-solid fa-flask"
    use: "predefined"
KEYCLOAK:
  OPENID_CONFIG_URI: "https://iam.ideaconsult.net/realms/nano/.well-known/openid-configuration"
  JWT_AUDIENCE: "account"
  JWT_ISSUER: "https://iam.ideaconsult.net/realms/nano"