---
KEYCLOAK:
  JWT_AUDIENCE: account
  JWT_ISSUER: https://iam.ideaconsult.net/realms/nano
  OPENID_CONFIG_URI: https://iam.ideaconsult.net/realms/nano/.well-known/openid-configuration
SOLR_COLLECTIONS:
  collections:
    - description: 'Plastic: SLoPP, SLoPP-E and Ocean Polymers Raman Spectral Libraries'
      license: TBD
      name: plastic
      roles:
        - public
    - description: RRUFF
      license: TBD
      name: rruf
      roles:
        - public
    - description: CHARISMA
      license: TBD
      name: charisma-public
      roles:
        - public
    - description: POLYRISK
      license: TBD
      name: polyrisk_spectra
      roles:
        - polyrisk
    - description: CHARISMA non-public
      license: TBD
      name: charisma-private
      roles:
        - charisma
  default: plastic
SOLR_DOCS:
  - study
SOLR_FIELDS:
  - field: q_provider
    icon: fa6/FaUser
    name: Data provider
    search: /db/query/field
  - field: q_reference
    icon: fa6/FaBookOpen
    name: Investigation
    search: /db/query/field
  - field: qdynamic.name_s
    icon: fa6/FaVial
    name: Sample
    search: /db/query/field/terms
    use: qdynamic
  - field: publicname_s
    icon: fa6/FaCube
    name: Material
    search: /db/query/field/terms
  - field: qdynamic.instrument_s
    icon: fa6/FaMicroscope
    name: Instrument
    search: /db/query/field/terms
    use: qdynamic
  - field: q_method
    icon: fa6/FaFlaskVial
    name: Method
    search: /db/query/field
  - field: qdynamic.type_s
    icon: fa6/FaFileLines
    name: Documents
    search: /db/query/field
    use: qdynamic
SOLR_ROOT: https://solr-kc.ideaconsult.net/solr/
SOLR_SIMILARITY:
  - name: Raman spectrum
    vector: spectrum_p1024
SOLR_VECTOR: spectrum_p1024
application_name: Spectra search
nmparse_url: https://api.ideaconsult.net/gracious/enm/gracious/nmparser
upload_dir: uploads
