---
KEYCLOAK:
  JWT_AUDIENCE: account
  JWT_ISSUER: https://iam.ideaconsult.net/realms/nano
  OPENID_CONFIG_URI: https://iam.ideaconsult.net/realms/nano/.well-known/openid-configuration
SOLR_COLLECTIONS:
  collections:
    - description: CHARISMA
      license: TBD
      name: charisma
      roles:
        - public
    - description: CHARISMA protected
      license: TBD
      name: charisma_protected
      roles:
        - charisma
        - test-role-1
    - description: GRACIOUS
      license: TBD
      name: gracious
      roles:
        - public
    - description: POLYRISK
      license: TBD
      name: polyrisk
      roles:
        - polyrisk
    - description: Nanoreg2
      license: TBD
      name: nanoreg2
      roles:
        - public
    - description: PlasticMap
      license: TBD
      name: ambitlri_plasticmap
      roles:
        - public
    - description: Repeated Dose tox database
      license: TBD
      name: repdose
      roles:
        - public
    - description: OpenFoodTox database
      license: TBD
      name: openfoodtox
      roles:
        - public
    - description: AopMapper
      license: TBD
      name: aop4enm
      roles:
        - public
    - description: DSSTox https://www.epa.gov/comptox-tools/distributed-structure-searchable-toxicity-dsstox-database
      license: Public
      name: dsstox
      roles:
        - public       
    - description: VEGA QSAR predictions
      license: Public
      name: vega
      roles:
        - public         
  default: charisma
SOLR_DOCS:
  - study
  - aop
  - assay
  - substance
  - key_event
  - stressor
  - prediction
  - chemical
  - inventory
  - metadata
SOLR_FIELDS:
  - field: q_provider
    icon: fa6/FaUser
    name: Data provider
    search: /db/query/field
  - field: q_reference
    icon: fa6/FaBookOpen
    name: Investigation
    search: /db/query/field
  - field: qdynamic.name_s
    icon: fa6/FaVial
    name: Sample
    search: /db/query/field/terms
    use: qdynamic
  - field: publicname_s
    icon: fa6/FaCube
    name: Material
    search: /db/query/field/terms
  - field: qdynamic.instrument_s
    icon: fa6/FaMicroscope
    name: Instrument
    search: /db/query/field/terms
    use: qdynamic
  - field: q_method
    icon: fa6/FaFlaskVial
    name: Method
    search: /db/query/field
  - field: qdynamic.type_s
    icon: fa6/FaFileLines
    name: Documents
    search: /db/query/field
    use: qdynamic
SOLR_ROOT: https://solr-kc.ideaconsult.net/solr/
SOLR_SIMILARITY:
  - name: Raman spectrum
    vector: spectrum_p1024
  - name: Chemical
    vector: dense_512
SOLR_VECTOR: spectrum_p1024
application_name: NAMbit (dev)
nmparse_url: https://api.ideaconsult.net/gracious/enm/gracious/nmparser
upload_dir: uploads
