---
KEYCLOAK:
  JWT_AUDIENCE: account
  JWT_ISSUER: https://iam.ideaconsult.net/realms/nano
  OPENID_CONFIG_URI: https://iam.ideaconsult.net/realms/nano/.well-known/openid-configuration
SOLR_COLLECTIONS:
  collections:
    - description: NANOREG eNanoMapper database
      license: CC-BY-NC
      name: nanoreg
      roles:
        - public
    - description: Nanoreg2 eNanoMapper database
      license: CC-BY-NC
      name: nanoreg
      roles:
        - public        
    - description: GRACIOUS eNanoMapper database
      license: TBD
      name: gracious
      roles:
        - public
    - description: caLIBRAte eNanoMapper database
      license: TBD
      name: calibrate
      roles:
        - public        
    - description: HARMLESS eNanoMapper database
      license: TBD
      name: harmless
      roles:
        - harmless  
    - description: NanoInformatix eNanoMapper database
      license: TBD
      name: nanoinformatix
      roles:
        - nanoinformatix          
    - description: PATROLS eNanoMapper database
      license: TBD
      name: patrols
      roles:
        - patrols
    - description: RiskGone eNanoMapper database
      license: TBD
      name: riskgone
      roles:
        - riskgone
    - description: RiskGone eNanoMapper database
      license: TBD
      name: riskgone
      roles:
        - riskgone
    - description: SABYDOMA eNanoMapper database
      license: TBD
      name: sabydoma
      roles:
        - sabydoma
    - description: SBD4NANO eNanoMapper database
      license: TBD
      name: sbd4nano
      roles:
        - sbd4nano        
    - description: AopMapper
      license: TBD
      name: aop4enm
      roles:
        - public
  default: nanoreg
SOLR_DOCS:
  - study
  - aop
  - assay
  - substance
  - key_event
  - stressor
  - prediction
  - chemical
  - inventory
  - metadata
SOLR_FIELDS:
  - field: q_provider
    icon: fa6/FaUser
    name: Data provider
    search: /db/query/field
  - field: q_reference
    icon: fa6/FaBookOpen
    name: Investigation
    search: /db/query/field
  - field: qdynamic.name_s
    icon: fa6/FaVial
    name: Sample
    search: /db/query/field/terms
    use: qdynamic
  - field: publicname_s
    icon: fa6/FaCube
    name: Material
    search: /db/query/field/terms
  - field: qdynamic.instrument_s
    icon: fa6/FaMicroscope
    name: Instrument
    search: /db/query/field/terms
    use: qdynamic
  - field: q_method
    icon: fa6/FaFlaskVial
    name: Method
    search: /db/query/field
  - field: qdynamic.type_s
    icon: fa6/FaFileLines
    name: Documents
    search: /db/query/field
    use: qdynamic
SOLR_ROOT: https://solr-kc.ideaconsult.net/solr/
SOLR_SIMILARITY:
  - name: Raman spectrum
    vector: spectrum_p1024
  - name: Chemical
    vector: dense_512
SOLR_VECTOR: spectrum_p1024
application_name: Raman Spectra search
nmparse_url: https://api.ideaconsult.net/gracious/enm/gracious/nmparser
upload_dir: uploads
